#!/usr/bin/env bun
/**
 * Bootstrap test fixtures for md-anything.
 * Generates binary fixtures (PDF, EPUB) into tests/generated-fixtures/
 */

import { mkdir, writeFile, rm } from "node:fs/promises";
import { join } from "node:path";

const OUT_DIR = join(import.meta.dir, "../tests/generated-fixtures");

async function ensureDir(dir: string): Promise<void> {
  await mkdir(dir, { recursive: true });
}

async function generateMinimalPdf(outPath: string): Promise<void> {
  const pdf = `%PDF-1.4
1 0 obj
<< /Type /Catalog /Pages 2 0 R >>
endobj

2 0 obj
<< /Type /Pages /Kids [3 0 R] /Count 1 >>
endobj

3 0 obj
<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792]
   /Contents 4 0 R /Resources << /Font << /F1 5 0 R >> >> >>
endobj

4 0 obj
<< /Length 44 >>
stream
BT /F1 12 Tf 100 700 Td (Hello from md-anything PDF) Tj ET
endstream
endobj

5 0 obj
<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>
endobj

xref
0 6
0000000000 65535 f 
0000000009 00000 n 
0000000058 00000 n 
0000000115 00000 n 
0000000266 00000 n 
0000000360 00000 n 

trailer
<< /Size 6 /Root 1 0 R >>
startxref
441
%%EOF`;

  await writeFile(outPath, pdf, "utf-8");
  console.log(`✅ Generated PDF: ${outPath}`);
}

async function generateMinimalEpub(outPath: string): Promise<void> {
  const { spawnSync } = await import("node:child_process");
  const { mkdtemp } = await import("node:fs/promises");
  const { tmpdir } = await import("node:os");

  const tmpDir = await mkdtemp(join(tmpdir(), "md-anything-epub-"));

  try {
    await mkdir(join(tmpDir, "META-INF"), { recursive: true });
    await mkdir(join(tmpDir, "OEBPS"), { recursive: true });

    await writeFile(join(tmpDir, "mimetype"), "application/epub+zip");

    await writeFile(join(tmpDir, "META-INF", "container.xml"), `<?xml version="1.0" encoding="UTF-8"?>
<container version="1.0" xmlns="urn:oasis:names:tc:opendocument:xmlns:container">
  <rootfiles>
    <rootfile full-path="OEBPS/content.opf" media-type="application/oebps-package+xml"/>
  </rootfiles>
</container>`);

    await writeFile(join(tmpDir, "OEBPS", "content.opf"), `<?xml version="1.0" encoding="UTF-8"?>
<package xmlns="http://www.idpf.org/2007/opf" version="2.0" unique-identifier="uid">
  <metadata xmlns:dc="http://purl.org/dc/elements/1.1/">
    <dc:title>md-anything Test EPUB</dc:title>
    <dc:creator>md-anything</dc:creator>
    <dc:identifier id="uid">md-anything-test-epub-001</dc:identifier>
    <dc:language>en</dc:language>
  </metadata>
  <manifest>
    <item id="chapter1" href="chapter1.xhtml" media-type="application/xhtml+xml"/>
    <item id="ncx" href="toc.ncx" media-type="application/x-dtbncx+xml"/>
  </manifest>
  <spine toc="ncx">
    <itemref idref="chapter1"/>
  </spine>
</package>`);

    await writeFile(join(tmpDir, "OEBPS", "chapter1.xhtml"), `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head><title>Chapter One</title></head>
<body>
<h1>Chapter One: Hello from md-anything</h1>
<p>This is a test EPUB generated by the md-anything fixture bootstrap script.</p>
<p>It contains real text content that can be extracted and converted to Markdown.</p>
</body>
</html>`);

    await writeFile(join(tmpDir, "OEBPS", "toc.ncx"), `<?xml version="1.0" encoding="UTF-8"?>
<ncx xmlns="http://www.daisy.org/z3986/2005/ncx/" version="2005-1">
  <head>
    <meta name="dtb:uid" content="md-anything-test-epub-001"/>
  </head>
  <docTitle><text>md-anything Test EPUB</text></docTitle>
  <navMap>
    <navPoint id="chapter1" playOrder="1">
      <navLabel><text>Chapter One</text></navLabel>
      <content src="chapter1.xhtml"/>
    </navPoint>
  </navMap>
</ncx>`);

    const result = spawnSync(
      "bash",
      [
        "-c",
        `cd "${tmpDir}" && zip -X0 "${outPath}" mimetype && zip -r "${outPath}" META-INF OEBPS`,
      ],
      { encoding: "utf-8" },
    );

    if (result.status === 0) {
      console.log(`✅ Generated EPUB: ${outPath}`);
    } else {
      console.warn(`⚠️  zip command failed: ${result.stderr}`);
      await writeFile(outPath, "EPUB generation failed - zip not available", "utf-8");
    }
  } finally {
    await rm(tmpDir, { recursive: true, force: true });
  }
}

async function generateMobiIfAvailable(epubPath: string, outPath: string): Promise<void> {
  const { spawnSync } = await import("node:child_process");

  const which = spawnSync("which", ["ebook-convert"], { encoding: "utf-8" });
  if (which.status !== 0) {
    console.log("⏭️  Skipping MOBI generation (ebook-convert not available)");
    return;
  }

  const result = spawnSync("ebook-convert", [epubPath, outPath], { encoding: "utf-8" });
  if (result.status === 0) {
    console.log(`✅ Generated MOBI: ${outPath}`);
  } else {
    console.warn(`⚠️  MOBI generation failed: ${result.stderr}`);
  }
}

async function main(): Promise<void> {
  console.log("🔧 Bootstrapping md-anything test fixtures...\n");

  await ensureDir(OUT_DIR);

  const pdfPath = join(OUT_DIR, "sample.pdf");
  const epubPath = join(OUT_DIR, "sample.epub");
  const mobiPath = join(OUT_DIR, "sample.mobi");

  await generateMinimalPdf(pdfPath);
  await generateMinimalEpub(epubPath);
  await generateMobiIfAvailable(epubPath, mobiPath);

  console.log("\n✅ Fixture bootstrap complete.");
  console.log(`   Output dir: ${OUT_DIR}`);
  console.log("   (This directory is gitignored — regenerate with: bun run test:fixtures)\n");
}

main().catch((err) => {
  console.error("Bootstrap failed:", err);
  process.exit(1);
});
